apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: onboarding-workflow-tile
  title: Onboard User to Org
  description: Separate workflow to invite user and set CODEOWNERS
spec:
  owner: user:pakaashok
  type: service

  parameters:
    - title: Onboarding Details
      required: [githubUser, repoName]
      properties:
        githubUser:
          type: string
          title: GitHub Username
        repoName:
          type: string
          title: New Repository Name

  steps:
    - id: fetch-onboarding
      name: Fetch Onboarding Files
      action: fetch:template
      input:
        url: ./onboarding-skeleton
        values:
          githubUser: ${{ parameters.githubUser }}

    - id: publish-onboarding
      name: Create Onboarding Repo
      action: publish:github
      input:
        repoUrl: 'github.com?owner=pakaashok&repo=${{ parameters.repoName }}'
        defaultBranch: main
        description: 'Onboarding repo for ${{ parameters.githubUser }}'
        # FIXED: Setting this to true allows the GitHub Action 
        # to see the ORG_ADMIN_TOKEN on the GitHub Free plan.
        public: true