apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: onboarding-workflow-tile # MUST be different from 'create-app-repo'
  title: Onboard User to Org
  description: Separate workflow to invite user and set CODEOWNERS
spec:
  owner: user:pakaashok
  type: service

  parameters:
    - title: Onboarding Details
      required: [githubUser, repoName]
      properties:
        githubUser:
          type: string
          title: GitHub Username
        repoName:
          type: string
          title: New Repository Name

  steps:
    - id: fetch-onboarding
      name: Fetch Onboarding Files
      action: fetch:template
      input:
        url: ./onboarding-skeleton # Ensure this folder exists
        values:
          githubUser: ${{ parameters.githubUser }}

    - id: publish-onboarding
      name: Create Onboarding Repo
      action: publish:github
      input:
        allowedHosts: ['github.com']
        repoUrl: 'github.com?owner=pakaashok&repo=${{ parameters.repoName }}'