apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: onboarding-workflow-tile
  title: Onboard User to Org
  description: Automation to create repo and teams

spec:
  # 'owner' is now a parameter or generic
  owner: guest
  type: service

  parameters:
    - title: GitHub Organization Details
      required: [githubOrg, githubUser, repoName]
      properties:
        githubOrg:
          type: string
          title: GitHub Organization Name
          default: "your-org-name"
        githubUser:
          type: string
          title: Target GitHub Username
        repoName:
          type: string
          title: New Repository Name
        teamName:
          type: string
          title: New Team Name

  steps:
    - id: fetch-onboarding
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./onboarding-skeleton
        values:
          githubUser: ${{ parameters.githubUser }}

    - id: publish-onboarding
      name: Create GitHub Repository
      action: publish:github
      input:
        # Dynamically uses the Org name provided in the UI
        repoUrl: 'github.com?owner=${{ parameters.githubOrg }}&repo=${{ parameters.repoName }}'
        defaultBranch: main
        repoVisibility: public

    - id: trigger-automation
      name: Trigger Actions
      action: github:actions:dispatch
      input:
        repoUrl: 'github.com?owner=${{ parameters.githubOrg }}&repo=platform-automation'
        workflowId: create-team.yml
        branchOrTagName: main
        workflowInputs:
          team_name: ${{ parameters.teamName }}
          github_user: ${{ parameters.githubUser }}
